import type { INodeProperties } from 'n8n-workflow';

const onlyAnalytics = { resource: ['analytics'] };

export const analyticsProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: onlyAnalytics },
		options: [
			{
				name: 'Get Overview',
				value: 'overview',
				action: 'Get an analytics overview',
				description: 'Workspace totals for a date window with a comparison to the previous window',
			},
			{
				name: 'Get Platform Breakdown',
				value: 'platformBreakdown',
				action: 'Get a platform breakdown',
				description: 'The overview metrics, one row per platform',
			},
			{
				name: 'Get Post Analytics',
				value: 'posts',
				action: 'Get per post analytics',
				description: 'Metrics for every tracked post published in the window',
			},
			{
				name: 'Get Timeseries',
				value: 'timeseries',
				action: 'Get an analytics timeseries',
				description: 'Metrics bucketed by day, week or month',
			},
		],
		default: 'overview',
	},
	{
		displayName: 'From',
		name: 'from',
		type: 'dateTime',
		required: true,
		default: '',
		displayOptions: { show: onlyAnalytics },
		description: 'Start of the reporting window',
	},
	{
		displayName: 'To',
		name: 'to',
		type: 'dateTime',
		required: true,
		default: '',
		displayOptions: { show: onlyAnalytics },
		description: 'End of the reporting window',
	},
	{
		displayName: 'Platforms',
		name: 'platforms',
		type: 'multiOptions',
		options: [
			{ name: 'Bluesky', value: 'BLUESKY' },
			{ name: 'Facebook', value: 'FACEBOOK' },
			{ name: 'Instagram', value: 'INSTAGRAM' },
			{ name: 'LinkedIn', value: 'LINKEDIN' },
			{ name: 'Pinterest', value: 'PINTEREST' },
			{ name: 'Threads', value: 'THREADS' },
			{ name: 'TikTok', value: 'TIKTOK' },
			{ name: 'YouTube', value: 'YOUTUBE' },
		],
		default: [],
		displayOptions: { show: onlyAnalytics },
		description: 'Leave empty for every platform with analytics',
	},
	{
		displayName: 'Interval',
		name: 'interval',
		type: 'options',
		options: [
			{ name: 'Day', value: 'DAY' },
			{ name: 'Month', value: 'MONTH' },
			{ name: 'Week', value: 'WEEK' },
		],
		default: 'DAY',
		displayOptions: { show: { resource: ['analytics'], operation: ['timeseries'] } },
	},
	{
		displayName: 'Sort By',
		name: 'sortBy',
		type: 'options',
		options: [
			{ name: 'Clicks', value: 'CLICKS' },
			{ name: 'Comments', value: 'COMMENTS' },
			{ name: 'Engagement Rate', value: 'ENGAGEMENT_RATE' },
			{ name: 'Impressions', value: 'IMPRESSIONS' },
			{ name: 'Likes', value: 'LIKES' },
			{ name: 'Published At', value: 'PUBLISHED_AT' },
			{ name: 'Saves', value: 'SAVES' },
			{ name: 'Shares', value: 'SHARES' },
			{ name: 'Views', value: 'VIEWS' },
		],
		default: 'PUBLISHED_AT',
		displayOptions: { show: { resource: ['analytics'], operation: ['posts'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: { show: { resource: ['analytics'], operation: ['posts'] } },
		description: 'Max number of results to return',
	},
];
