import type { INodeProperties } from 'n8n-workflow';

const onlyPosts = { resource: ['post'] };
const withPostId = { resource: ['post'], operation: ['delete', 'get', 'getResults', 'publishDraft', 'retry'] };

export const postProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: onlyPosts },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a post',
				description: 'Publish now, schedule, or save a draft on one or more accounts',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a post',
				description: 'Delete a draft or scheduled post',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a post',
				description: 'Get one post with its per-platform status',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many posts',
				description: 'List posts, newest first',
			},
			{
				name: 'Get Results',
				value: 'getResults',
				action: 'Get publishing results of a post',
				description: 'Get the publishing outcome of a post on each platform',
			},
			{
				name: 'Publish Draft',
				value: 'publishDraft',
				action: 'Publish a draft post',
				description: 'Publish a draft now or schedule it',
			},
			{
				name: 'Retry Failed Platforms',
				value: 'retry',
				action: 'Retry failed platforms of a post',
				description: 'Re-queue publishing for every platform that failed',
			},
		],
		default: 'create',
	},
	{
		displayName: 'Post ID',
		name: 'postId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: withPostId },
		description: 'ID returned when the post was created, or from Get Many',
	},
	{
		displayName: 'Account Names or IDs',
		name: 'accountIds',
		type: 'multiOptions',
		required: true,
		default: [],
		typeOptions: { loadOptionsMethod: 'getAccounts' },
		displayOptions: { show: { resource: ['post'], operation: ['create'] } },
		description:
			'Connected accounts to post from. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Content Type',
		name: 'contentType',
		type: 'options',
		options: [
			{ name: 'Carousel', value: 'CAROUSEL' },
			{ name: 'Image', value: 'IMAGE' },
			{ name: 'Text', value: 'TEXT' },
			{ name: 'Video', value: 'VIDEO' },
		],
		default: 'TEXT',
		displayOptions: { show: { resource: ['post'], operation: ['create'] } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		displayOptions: { show: { resource: ['post'], operation: ['create'] } },
		description: 'Caption shared across the selected platforms',
	},
	{
		displayName: 'Media URLs',
		name: 'mediaUrls',
		type: 'string',
		default: '',
		placeholder: 'https://example.com/photo.jpg, https://example.com/clip.mp4',
		displayOptions: { show: { resource: ['post'], operation: ['create'] } },
		description:
			'Comma-separated public URLs of JPEG, PNG, WebP, MP4 or QuickTime files. Each file is copied into AdaptlyPost storage before posting.',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['post'], operation: ['create'] } },
		options: [
			{
				displayName: 'Facebook Post Type',
				name: 'facebookPostType',
				type: 'options',
				options: [
					{ name: 'Feed', value: 'FEED' },
					{ name: 'Reel', value: 'REEL' },
					{ name: 'Story', value: 'STORY' },
				],
				default: 'FEED',
			},
			{
				displayName: 'Instagram Post Type',
				name: 'instagramPostType',
				type: 'options',
				options: [
					{ name: 'Feed', value: 'FEED' },
					{ name: 'Reel', value: 'REEL' },
					{ name: 'Story', value: 'STORY' },
				],
				default: 'FEED',
			},
			{
				displayName: 'Pinterest Board ID',
				name: 'pinterestBoard',
				type: 'string',
				default: '',
				description: 'Required when a Pinterest account is selected',
			},
			{
				displayName: 'Pinterest Link',
				name: 'pinterestLink',
				type: 'string',
				default: '',
				description: 'Destination link for the pin',
			},
			{
				displayName: 'Save as Draft',
				name: 'saveAsDraft',
				type: 'boolean',
				default: false,
				description: 'Whether to store the post without publishing or scheduling it',
			},
			{
				displayName: 'Scheduled At',
				name: 'scheduledAt',
				type: 'dateTime',
				default: '',
				description: 'Leave empty to publish immediately',
			},
			{
				displayName: 'TikTok Privacy',
				name: 'tiktokPrivacyLevel',
				type: 'options',
				options: [
					{ name: 'Followers', value: 'FOLLOWER_OF_CREATOR' },
					{ name: 'Friends', value: 'MUTUAL_FOLLOW_FRIENDS' },
					{ name: 'Only Me', value: 'SELF_ONLY' },
					{ name: 'Public', value: 'PUBLIC_TO_EVERYONE' },
				],
				default: 'PUBLIC_TO_EVERYONE',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: 'UTC',
				description: 'IANA name such as America/New_York, stored with the post for display',
			},
			{
				displayName: 'YouTube Format',
				name: 'youtubePostType',
				type: 'options',
				options: [
					{ name: 'Shorts', value: 'SHORTS' },
					{ name: 'Video', value: 'VIDEO' },
				],
				default: 'VIDEO',
			},
			{
				displayName: 'YouTube Privacy',
				name: 'youtubePrivacyStatus',
				type: 'options',
				options: [
					{ name: 'Private', value: 'private' },
					{ name: 'Public', value: 'public' },
					{ name: 'Unlisted', value: 'unlisted' },
				],
				default: 'public',
			},
			{
				displayName: 'YouTube Video Title',
				name: 'youtubeTitle',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Scheduled At',
		name: 'scheduledAt',
		type: 'dateTime',
		default: '',
		displayOptions: { show: { resource: ['post'], operation: ['publishDraft'] } },
		description: 'Leave empty to publish immediately',
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: 'UTC',
		displayOptions: { show: { resource: ['post'], operation: ['publishDraft'] } },
		description: 'IANA name such as America/New_York',
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['post'], operation: ['getAll'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: { show: { resource: ['post'], operation: ['getAll'], returnAll: [false] } },
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['post'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'dateTime',
				default: '',
				description: 'Upper bound on the scheduled time, or creation time for posts never scheduled',
			},
			{
				displayName: 'Platforms',
				name: 'platforms',
				type: 'multiOptions',
				options: [
					{ name: 'Bluesky', value: 'BLUESKY' },
					{ name: 'Facebook', value: 'FACEBOOK' },
					{ name: 'Instagram', value: 'INSTAGRAM' },
					{ name: 'LinkedIn', value: 'LINKEDIN' },
					{ name: 'Pinterest', value: 'PINTEREST' },
					{ name: 'Threads', value: 'THREADS' },
					{ name: 'TikTok', value: 'TIKTOK' },
					{ name: 'X (Twitter)', value: 'TWITTER' },
					{ name: 'YouTube', value: 'YOUTUBE' },
				],
				default: [],
				description: 'Only posts targeting any of these platforms',
			},
			{
				displayName: 'Sort Order',
				name: 'sortOrder',
				type: 'options',
				options: [
					{ name: 'Newest First', value: 'NEWEST' },
					{ name: 'Oldest First', value: 'OLDEST' },
				],
				default: 'NEWEST',
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'dateTime',
				default: '',
				description: 'Lower bound on the scheduled time, or creation time for posts never scheduled',
			},
			{
				displayName: 'Statuses',
				name: 'statuses',
				type: 'multiOptions',
				options: [
					{ name: 'Completed', value: 'COMPLETED' },
					{ name: 'Draft', value: 'DRAFT' },
					{ name: 'Failed', value: 'FAILED' },
					{ name: 'Partial Failure', value: 'PARTIAL_FAILURE' },
					{ name: 'Pending', value: 'PENDING' },
					{ name: 'Publishing', value: 'PUBLISHING' },
					{ name: 'Scheduled', value: 'SCHEDULED' },
				],
				default: [],
			},
		],
	},
];
